<!-- XXXlongname -->
<!-- XXXid -->
<!-- XXX -->
<!-- CCCid -->
<!-- CCC -->


```{r XXXideuCCC, fig.show="hold", fig.height=7, fig.width=12, fig.cap="XXXlongname clusters based on time period CCC, computed using complete linkage hierarchical clustering based on Euclidean distance."}
CVsplines[["XXXid"]]$spline %>% left_join(euclust[["XXXid"]]$`CCC`$cl) %>% filter(!is.na(cl), day<=36*365.25/12) %>% ggplot(aes(x=day, y=XXX, group=subjid, color=paste("Cluster ", cl))) + geom_vline(xintercept = 30) + geom_vline(xintercept=364) + geom_line() + theme_bw() + scale_color_discrete("") + scale_x_continuous(trans=scales::boxcox_trans(CVsplines[["XXXid"]]$lambda$x, 1)) + scale_y_continuous(trans=scales::boxcox_trans(CVsplines[["XXXid"]]$lambda$y)) 
```

```{r XXXidpvlust, fig.cap="XXXlongname. Multiscale bootstrap resampling. Clusters with alpha>=0.90 are shown to the right", fig.show="hold", fig.height=7, fig.width=7, out.width="50%"}
XXXidCCCid <- Eucluster(CVsplines[["XXXid"]]$splw, CVsplines[["XXXid"]]$spline, CVsplines[["XXXid"]]$lambda, timewindows$`CCC`, "CCC", time="day", value="XXX", pv=TRUE)
plot(XXXidCCCid$pvc)
plot(XXXidCCCid$pvpl)
```


```{r XXXideuCCCheatmap, fig.show="hold", fig.height=7, fig.width=12, fig.cap="XXXlongname clusters based on time period CCC, computed using complete linkage hierarchical clustering based on Euclidean distance."}
NY <- c('Fever', 'Headache', 'Nightsweats', 'Myalgia', 'Fatigue', 'Skinrash', 'Oralulcers', 'Pharyngitis', 'Lymphadenopathy', 'Diarrhea', 'Anorexia')

clname <- c("cluster")
names(clname) <- "XXXidCCCid"

ph <- clinc %>% left_join(euclust[["XXXid"]]$`CCC`$cl) %>% mutate(across(c(ARS, all_of(NY)), ~factor(., levels=c("No", "Yes"))), cluster=factor(cl), across(c(Site, Sex, Risk_grp, Subtype), ~factor(.))) %>% rename(clname) %>% dplyr::select(subjid, ARS, all_of(c(NY, names(clname))), Site, Risk_grp, Sex, Age, Subtype)

Xw <- Xw %>% left_join(ph %>% dplyr::select(subjid, all_of("XXXidCCCid")))
ph <- ph %>% column_to_rownames("subjid")

bwNY=c("No"="gray", "Yes"="black")
annot_cols <- list(Risk_grp=c(MSM="black", DC="orange", HET="cornflowerblue"))
for (nm in NY) annot_cols[[nm]] <- bwNY
z <- CVsplines[["XXXid"]]$splw %>% dplyr::filter(day>=30, day<=365.25) %>% dplyr::select(which(colMeans(is.na(.))==0))
pheatmap(t(z[, -1]), cluster_cols = FALSE, annotation_row = ph[colnames(z)[-1],], annotation_colors =annot_cols) 
```

\FloatBarrier

```{r XXXidCCCid}
tab <- tab1(names(ph)[!grepl("^cl", names(ph))], df=ph %>% filter(!is.na(all_of("XXXidCCCid"))), y="XXXidCCCid")
options(knitr.kable.NA = '')
tab %>% mutate(variable=cell_spec(variable, bold=!is.na(test)), p=ifelse(!is.na(p), sprintf("%.3g", p), p)) %>% dplyr::select(-var) %>% kable(escape=FALSE, row.names = FALSE, caption="Summary of associations between clinical parameters and XXXlongname clusters calculated using data from CCC and complete linkage hierarchical clustering based on Euclidean distance.") %>% kable_styling() 
```

### Linear regression, XXXlongname CCC clusters

Linear regressions are performed separately for each time point (or difference) and protein, to assess the association between protein value and XXXlongname CCC clusters. Age is included as a covariate in the models.

```{r XXXidlmCCCid}
xvar <- "XXXidCCCid"
lmres[[xvar]] <- sapply(c("v0", "v1", "v2", "v10", "v20", "v21"), function(y) Xw %>% group_by(Protein, exp) %>% summarize(lmmod(df=cur_data(), y=y, var=xvar), .groups="drop") %>% mutate(visit=y) %>% relocate(visit, ), simplify = FALSE, USE.NAMES = TRUE)
lmres[[xvar]] <- lapply(lmres[[xvar]], function(x) x %>% left_join(proteins, by=c(Protein="id")) %>% relocate(c("UniProt", "hgnc_symbol"), .after="Protein")) 
openxlsx::write.xlsx(lmres[[xvar]], file="XXXid_lm_CCCidage.xlsx")
openxlsx::write.xlsx(lapply(lmres[[xvar]], function(z) z %>% filter(grepl(xvar, variable)) %>% arrange(p)), file="XXXid_lm_CCCid.xlsx")
```

\FloatBarrier

```{r XXXidCCCidQQunif, fig.cap="QQplots of XXXid CCC cluster p-values. Observed p-values vs expected p-values."}
pl <- do.call("rbind", lmres[[xvar]]) %>% filter(grepl(xvar, variable)) %>% mutate(visit=factor(visit, names(lmres[[xvar]]))) %>% group_by(visit) %>% mutate(exp.p=(rank(p, ties.method="first")+.5)/(length(p)+1)) %>% ggplot(aes(x=-log10(exp.p), y=-log10(p))) + geom_point() + geom_abline(intercept = 0, slope=1) + facet_wrap(~visit) + theme_bw()
plot(pl)
```

\FloatBarrier

```{r XXXidCCCidlmtabs, results="asis"}
for (v in names(lmres[[xvar]])) {
  print(lmres[[xvar]][[v]] %>% filter(grepl(xvar, variable)) %>% arrange(p) %>% head() %>% dplyr::select(Protein, hgnc_symbol, Estimate, p) %>% rename(beta=Estimate) %>% kable(caption=sprintf("Top associations between protein value at visit %s and XXXlongname clusters based on CCC (complete linkage, Euclidean).", sapply(strsplit(v, ""), function(z) paste(z[-1], collapse=" - "))), label=v))
} 
```

