<!-- Viral Load -->
<!-- VL -->
<!-- vload -->
<!-- cl112m -->
<!-- 1-12m -->


```{r VLeu1-12m, fig.show="hold", fig.height=7, fig.width=12, fig.cap="Viral Load clusters based on time period 1-12m, computed using complete linkage hierarchical clustering based on Euclidean distance."}
CVsplines[["VL"]]$spline %>% left_join(euclust[["VL"]]$`1-12m`$cl) %>% filter(!is.na(cl), day<=36*365.25/12) %>% ggplot(aes(x=day, y=vload, group=subjid, color=paste("Cluster ", cl))) + geom_vline(xintercept = 30) + geom_vline(xintercept=364) + geom_line() + theme_bw() + scale_color_discrete("") + scale_x_continuous(trans=scales::boxcox_trans(CVsplines[["VL"]]$lambda$x, 1)) + scale_y_continuous(trans=scales::boxcox_trans(CVsplines[["VL"]]$lambda$y)) 
```

```{r VLpvlust, fig.cap="Viral Load. Multiscale bootstrap resampling. Clusters with alpha>=0.90 are shown to the right", fig.show="hold", fig.height=7, fig.width=7, out.width="50%"}
VLcl112m <- Eucluster(CVsplines[["VL"]]$splw, CVsplines[["VL"]]$spline, CVsplines[["VL"]]$lambda, timewindows$`1-12m`, "1-12m", time="day", value="vload", pv=TRUE)
plot(VLcl112m$pvc)
plot(VLcl112m$pvpl)
```


```{r VLeu1-12mheatmap, fig.show="hold", fig.height=7, fig.width=12, fig.cap="Viral Load clusters based on time period 1-12m, computed using complete linkage hierarchical clustering based on Euclidean distance."}
NY <- c('Fever', 'Headache', 'Nightsweats', 'Myalgia', 'Fatigue', 'Skinrash', 'Oralulcers', 'Pharyngitis', 'Lymphadenopathy', 'Diarrhea', 'Anorexia')

clname <- c("cluster")
names(clname) <- "VLcl112m"

ph <- clinc %>% left_join(euclust[["VL"]]$`1-12m`$cl) %>% mutate(across(c(ARS, all_of(NY)), ~factor(., levels=c("No", "Yes"))), cluster=factor(cl), across(c(Site, Sex, Risk_grp, Subtype), ~factor(.))) %>% rename(clname) %>% dplyr::select(subjid, ARS, all_of(c(NY, names(clname))), Site, Risk_grp, Sex, Age, Subtype)

Xw <- Xw %>% left_join(ph %>% dplyr::select(subjid, all_of("VLcl112m")))
ph <- ph %>% column_to_rownames("subjid")

bwNY=c("No"="gray", "Yes"="black")
annot_cols <- list(Risk_grp=c(MSM="black", DC="orange", HET="cornflowerblue"))
for (nm in NY) annot_cols[[nm]] <- bwNY
z <- CVsplines[["VL"]]$splw %>% dplyr::filter(day>=30, day<=365.25) %>% dplyr::select(which(colMeans(is.na(.))==0))
pheatmap(t(z[, -1]), cluster_cols = FALSE, annotation_row = ph[colnames(z)[-1],], annotation_colors =annot_cols) 
```

\FloatBarrier

```{r VLcl112m}
tab <- tab1(names(ph)[!grepl("^cl", names(ph))], df=ph %>% filter(!is.na(all_of("VLcl112m"))), y="VLcl112m")
options(knitr.kable.NA = '')
tab %>% mutate(variable=cell_spec(variable, bold=!is.na(test)), p=ifelse(!is.na(p), sprintf("%.3g", p), p)) %>% dplyr::select(-var) %>% kable(escape=FALSE, row.names = FALSE, caption="Summary of associations between clinical parameters and Viral Load clusters calculated using data from 1-12m and complete linkage hierarchical clustering based on Euclidean distance.") %>% kable_styling() 
```

### Linear regression, Viral Load 1-12m clusters

Linear regressions are performed separately for each time point (or difference) and protein, to assess the association between protein value and Viral Load 1-12m clusters. Age is included as a covariate in the models.

```{r VLlmcl112m}
xvar <- "VLcl112m"
lmres[[xvar]] <- sapply(c("v0", "v1", "v2", "v10", "v20", "v21"), function(y) Xw %>% filter(Protein %in% protkeep) %>% group_by(Protein) %>% summarize(lmmod(df=cur_data(), y=y, var=xvar), .groups="drop") %>% rename(p=Pr...t..) %>% mutate(visit=y) %>% relocate(visit, ), simplify = FALSE, USE.NAMES = TRUE)
lmres[[xvar]] <- lapply(lmres[[xvar]], function(x) x %>% left_join(proteins, by=c(Protein="id")) %>% relocate(c("UniProt", "hgnc_symbol"), .after="Protein")) 
openxlsx::write.xlsx(lmres[[xvar]], file="VL_lm_cl112mage.xlsx")
openxlsx::write.xlsx(lapply(lmres[[xvar]], function(z) z %>% filter(grepl(xvar, variable)) %>% arrange(p)), file="VL_lm_cl112m.xlsx")
```

\FloatBarrier

```{r VLcl112mQQunif, fig.cap="QQplots of VL 1-12m cluster p-values. Observed p-values vs expected p-values."}
pl <- do.call("rbind", lmres[[xvar]]) %>% filter(grepl(xvar, variable)) %>% mutate(visit=factor(visit, names(lmres[[xvar]]))) %>% group_by(visit) %>% mutate(exp.p=(rank(p, ties.method="first")+.5)/(length(p)+1)) %>% ggplot(aes(x=-log10(exp.p), y=-log10(p))) + geom_point() + geom_abline(intercept = 0, slope=1) + facet_wrap(~visit) + theme_bw()
plot(pl)
```

\FloatBarrier

```{r VLcl112mlmtabs, results="asis"}
for (v in names(lmres[[xvar]])) {
  print(lmres[[xvar]][[v]] %>% filter(grepl(xvar, variable)) %>% arrange(p) %>% head() %>% dplyr::select(Protein, hgnc_symbol, Estimate, p) %>% rename(beta=Estimate) %>% kable(caption=sprintf("Top associations between protein value at visit %s and Viral Load clusters based on 1-12m (complete linkage, Euclidean).", sapply(strsplit(v, ""), function(z) paste(z[-1], collapse=" - "))), label=v))
} 
```

